version: "3.8"
services:
  postgres-market-dev:
    image: postgres:latest
    domainname: postgres_auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-market
  redis-market-dev:
    image: redis:latest
    command: redis-server --save 60 1
    environment:
      ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "6379:6379"